- platform: template
  switches:
    braviatv:
      friendly_name: Fernseher
      icon_template: mdi:television
      value_template: "{{ is_state('media_player.sony_bravia_tv', 'on') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.sony_bravia_tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.sony_bravia_tv
