- id: '1561274952342'
  alias: (TEST) NTFY TV
  trigger:
  - event_data: {}
    event_type: ''
    platform: event
  condition: []
  action:
  - data:
      data:
        color: default
        duration: 5
        interrupt: 1
        position: center
        transparency: 0%
      message: Test
      title: Notification Title
    service: notify.tv
