- id: '1535720192997'
  alias: Feed Time 60g
  trigger:
  - at: '15:00:00'
    platform: time
  condition: []
  action:
  - data:
      feedamount: '60'
    service: rest_command.feeder_feed
- id: '1535742813512'
  alias: Feed Time 40g
  trigger:
  - at: 03:00
    platform: time
  condition: []
  action:
  - data:
      feedamount: 40g
    service: rest_command.feeder_feed
