- id: '1534528054933'
  alias: Rick MP
  trigger: []
  condition: []
  action:
  - data:
      entity_id: media_player.sony_bravia_tv
      media_content_id: https://www.youtube.com/watch?v=oHg5SJYRHA0
      media_content_type: video/youtube
    service: media_player.play_media
- id: '1534528083466'
  alias: Rick ME
  trigger: []
  condition: []
  action:
  - data:
      entity_id: media_player.sony_bravia_tv
      media_content_id: https://www.youtube.com/watch?v=oHg5SJYRHA0
      media_content_type: video/youtube
    service: media_extractor.play_media
