###
# Notification: Open windows
- id: wohnzimmer_feuchtigkeit
  alias: Wohnzimmer Feuchtigkeit
  hide_entity: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.wohnzimmer_humidity
      value_template: '{{ float(state.state) }}'
      above: 60
    - platform: numeric_state
      entity_id: sensor.dark_sky_humidity
      #value_template: '{{ states.sensor.wohnzimmer_humidity.state }}'
      below: 60
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.wohnzimmer_humidity
        value_template: >
          {% if is_state('sensor.wohnzimmer_humidity', 'nan') %}
            0.0
          {% else %}
            {{ states('sensor.wohnzimmer_humidity') }}
          {% endif %}
        above: 60
      - condition: numeric_state
        entity_id: sensor.dark_sky_humidity
        below: 60
      - condition: state
        entity_id: sensor.someone_at_home
        state: 'True'
  action:
    service: notify.telegram
    data:
      message: Wohnzimmer sollte gelueftet werden! (Luftfeuchtigkeit {{ states('sensor.wohnzimmer_humidity') }}%)

- id: schlafzimmer_feuchtigkeit
  alias: Schlafzimmer Feuchtigkeit
  hide_entity: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.schlafzimmer_humidity
      above: 60
    - platform: numeric_state
      entity_id: sensor.dark_sky_humidity
      below: 60
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.schlafzimmer_humidity
        value_template: >
          {% if is_state('sensor.schlafzimmer_humidity', 'nan') %}
            0.0
          {% else %}
            {{ states('sensor.schlafzimmer_humidity') }}
          {% endif %}
        above: 60
      - condition: numeric_state
        entity_id: sensor.dark_sky_humidity
        below: 60
      - condition: state
        entity_id: sensor.someone_at_home
        state: 'True'
  action:
    service: notify.telegram
    data:
      message: Schlafzimmer sollte gelueftet werden! (Luftfeuchtigkeit {{ states('sensor.schlafzimmer_humidity') }}%)


###
# Notification: Close windows; todo: distinguish between winter/not winter or cold temperatures in general
- id: badezimmer_fenster
  alias: Badezimmer Fenster
  trigger:
    - platform: state
      entity_id: binary_sensor.oeq0164835_state
      from: 'off'
      to: 'on'
      for:
        minutes: 15
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.dark_sky_temperature
        below: 10
  action:
    service: notify.telegram
    data:
      message: Badezimmer Fenster sollte nun geschlossen werden!

- id: schlafzimmer_fenster
  alias: Schlafzimmer Fenster
  trigger:
    - platform: state
      entity_id: binary_sensor.oeq0167636_state
      from: 'off'
      to: 'on'
      for:
        minutes: 12
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.dark_sky_temperature
        below: 10
  action:
    service: notify.telegram
    data:
      message: Schlafzimmer Fenster sollte nun geschlossen werden!

- id: wohnzimmer_fenster
  alias: Wohnzimmer Fenster
  trigger:
    - platform: state
      entity_id: binary_sensor.oeq0166378_state
      from: 'off'
      to: 'on'
      for:
        minutes: 12
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.dark_sky_temperature
        below: 10
  action:
    service: notify.telegram
    data:
      message: Wohnzimmer Fenster sollte nun geschlossen werden!


###
# Door alarms
- id: fenster_schliessen
  alias: Fenster schliessen
  trigger:
    - platform: state
      entity_id: binary_sensor.oeq0169426_state
      from: 'off'
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.oeq0164835_state
        state: 'on'
      - condition: state
        entity_id: binary_sensor.oeq0167636_state
        state: 'on'
      - condition: state
        entity_id: binary_sensor.oeq0166378_state
        state: 'on'
  action:
    service: notify.telegram
    data:
      message: Fenster schliessen!

- id: wohnzimmer_lampe_ausmachen
  alias: Wohnzimmer Lampe ausmachen
  trigger:
    - platform: state
      entity_id: binary_sensor.oeq0169426_state
      from: 'off'
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: light.wohnzimmer_lampe_1
        state: 'on'
      - condition: state
        entity_id: light.wohnzimmer_lampe_2
        state: 'on'
      - condition: state
        entity_id: light.wohnzimmer_lampe_3
        state: 'on'
      - condition: state
        entity_id: light.wohnzimmer_lampe_4
        state: 'on'
  action:
    service: notify.telegram
    data:
      message: Wohnzimmer Lampe ausmachen!

- id: kuechenlampe_ausmachen
  alias: Küchenlampe ausmachen
  trigger:
    - platform: state
      entity_id: binary_sensor.oeq0169426_state
      from: 'off'
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: light.kuechenlampe
        state: 'on'
  action:
    service: notify.telegram
    data:
      message: Küchenlampe ausmachen!

- id: badezimmer_lampe_ausmachen
  alias: Badezimmer Lampe ausmachen
  trigger:
    - platform: state
      entity_id: binary_sensor.oeq0169426_state
      from: 'off'
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: light.badezimmer_lampe
        state: 'on'
  action:
    service: notify.telegram
    data:
      message: Badezimmer Lampe ausmachen!

- id: schlafzimmer_lampe_ausmachen
  alias: Schlafzimmer Lampe ausmachen
  trigger:
    - platform: state
      entity_id: binary_sensor.oeq0169426_state
      from: 'off'
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: light.schlafzimmer_lampe
        state: 'on'
  action:
    service: notify.telegram
    data:
      message: Schlafzimmer Lampe ausmachen!
###
# Hifi plug; todo: remove this
- id: hifi_turn_on
  alias: Hifi Turn On
  hide_entity: true
  trigger:
#    - platform: state
#      entity_id: media_player.sony_bravia_tv
#      from: 'off'
#      to: 'on'
    - platform: state
      entity_id: media_player.denon
      from: 'off'
      to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.hifi_steckdose

#- alias: Hifi Turn Off
#  hide_entity: true
#  trigger:
#    - platform: state
#      entity_id: media_player.sony_bravia_tv
#      from: 'on'
#      to: 'off'
#    - platform: state
#      entity_id: media_player.denon
#      from: 'on'
#      to: 'off'
#  condition:
#    condition: and
#    conditions:
#      - condition: state
#        entity_id: media_player.sony_bravia_tv
#        state: 'off'
#      - condition: state
#        entity_id: media_player.denon
#        state: 'off'
#  action:
#    service: switch.turn_off
#    entity_id: switch.hifi_steckdose

###
# Updater
- id: update_notification
  alias: Update Available Notification
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.telegramtest
    data:
      message: 'Update for Home Assistant is available.'

