- id: '1561274952342'
  alias: (TEST) NTFY TV
  trigger:
  - event_data: {}
    event_type: ''
    platform: event
  condition: []
  action:
  - data:
      data:
        color: default
        duration: 5
        interrupt: 1
        position: center
        transparency: 0%
      message: Test
      title: Notification Title
    service: notify.tv
- id: '1574144981511'
  alias: FIX - Tradfri Badezimmer On
  description: ''
  trigger:
  - device_id: 70a79717fa2d409097a1a20468ceaad3
    domain: light
    entity_id: light.badezimmer_lampe_1
    platform: device
    type: turned_on
  - device_id: 9abd08daa7f64bbabf7ab8c185b483d0
    domain: light
    entity_id: light.badezimmer_lampe_2
    platform: device
    type: turned_on
  condition: []
  action:
  - data:
      entity_id: light.badezimmer
    service: light.turn_on
- id: '1574145061772'
  alias: FIX - Tradfri Badezimmer Off
  description: ''
  trigger:
  - device_id: 70a79717fa2d409097a1a20468ceaad3
    domain: light
    entity_id: light.badezimmer_lampe_1
    platform: device
    type: turned_off
  - device_id: 9abd08daa7f64bbabf7ab8c185b483d0
    domain: light
    entity_id: light.badezimmer_lampe_2
    platform: device
    type: turned_off
  condition: []
  action:
  - data:
      entity_id: light.badezimmer
    service: light.turn_off
- id: '1574145895611'
  alias: FIX - Tradfri Schlafzimmer On
  description: ''
  trigger:
  - device_id: c89645aa6a394ae8b2ef12b0a9f3de20
    domain: light
    entity_id: light.schlafzimmer_lampe_1
    for:
      hours: 0
      minutes: 0
      seconds: 0
    platform: device
    type: turned_on
  - device_id: 5d71c0e7fcd846cf9ef856b3036dda48
    domain: light
    entity_id: light.schlafzimmer_lampe_2
    for:
      hours: 0
      minutes: 0
      seconds: 0
    platform: device
    type: turned_on
  condition: []
  action:
  - data:
      entity_id: light.schlafzimmer
    service: light.turn_on
- id: '1574145927751'
  alias: FIX - Tradfri Schlafzimmer Off
  description: ''
  trigger:
  - device_id: c89645aa6a394ae8b2ef12b0a9f3de20
    domain: light
    entity_id: light.schlafzimmer_lampe_1
    for:
      hours: 0
      minutes: 0
      seconds: 0
    platform: device
    type: turned_off
  - device_id: 5d71c0e7fcd846cf9ef856b3036dda48
    domain: light
    entity_id: light.schlafzimmer_lampe_2
    for:
      hours: 0
      minutes: 0
      seconds: 0
    platform: device
    type: turned_off
  condition: []
  action:
  - data:
      entity_id: light.schlafzimmer
    service: light.turn_off
- id: '1575208030352'
  alias: Haustür
  description: ''
  trigger:
  - entity_id: binary_sensor.oeq0169426_state
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.oeq0164835_state
      state: 'on'
    - condition: state
      entity_id: binary_sensor.oeq0166378_state
      state: 'on'
    - condition: state
      entity_id: binary_sensor.oeq0167636_state
      state: 'on'
  action:
  - data:
      message: Ein Fenster ist noch geöffnet!
    service: notify.telegram
- id: '1575209500948'
  alias: NTFY - Schlafzimmer Fenster
  description: ''
  trigger:
  - entity_id: binary_sensor.oeq0167636_state
    for: 00:10:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Schlafzimmer Fenster war 10min geöffnet
    service: notify.telegram
- id: '1578513683867'
  alias: (TEST) CRITICAL NTFY Melina
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      data:
        push:
          sound:
            critical: 1
            name: default
            volume: 1
      message: Hallooooooo
      title: Test
    service: notify.mobile_app_msp_ip7
- id: '1579464490045'
  alias: Wohnzimmer Lichtschalter - An
  description: ''
  trigger:
  - device_id: 9ae4021053464b1188f3a8b365796f15
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_long_press
  condition: []
  action:
  - entity_id: light.wohnzimmer_stehlampe
    service: light.turn_on
- id: '1579464524100'
  alias: Wohnzimmer Lichtschalter - Aus
  description: ''
  trigger:
  - device_id: 9ae4021053464b1188f3a8b365796f15
    domain: deconz
    platform: device
    subtype: turn_off
    type: remote_button_long_press
  condition: []
  action:
  - entity_id: light.wohnzimmer_stehlampe
    service: light.turn_off
- id: '1581175680084'
  alias: New Automation
  description: ''
  trigger:
  - entity_id: binary_sensor.kueche_bewegungssensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - below: '10'
    condition: numeric_state
    entity_id: sensor.kueche_helligkeitssensor
  action:
  - entity_id: light.kueche
    service: light.turn_on
