- id: '1561274952342'
  alias: (TEST) NTFY TV
  trigger:
  - event_data: {}
    event_type: ''
    platform: event
  condition: []
  action:
  - data:
      data:
        color: default
        duration: 5
        interrupt: 1
        position: center
        transparency: 0%
      message: Test
      title: Notification Title
    service: notify.tv
- id: '1575208030352'
  alias: Haustür
  description: ''
  trigger:
  - entity_id: binary_sensor.oeq0169426_state
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.oeq0164835_state
      state: 'on'
    - condition: state
      entity_id: binary_sensor.oeq0166378_state
      state: 'on'
    - condition: state
      entity_id: binary_sensor.oeq0167636_state
      state: 'on'
  action:
  - data:
      message: Ein Fenster ist noch geöffnet!
    service: notify.telegram
- id: '1575209500948'
  alias: NTFY - Schlafzimmer Fenster
  description: ''
  trigger:
  - entity_id: binary_sensor.oeq0167636_state
    for: 00:10:00
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Schlafzimmer Fenster war 10min geöffnet
    service: notify.telegram
- id: '1578513683867'
  alias: (TEST) CRITICAL NTFY Melina
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      data:
        push:
          sound:
            critical: 1
            name: default
            volume: 1
      message: Hallooooooo
      title: Test
    service: notify.mobile_app_msp_ip7
- id: '1590863492632'
  alias: Küche Bewegung -> Küchenlampe An
  description: ''
  trigger:
  - device_id: 3b59816422944600b79ce4faccfc87ec
    domain: binary_sensor
    entity_id: binary_sensor.kueche_bewegungssensor
    platform: device
    type: motion
  condition:
  - above: '0'
    below: '30'
    condition: numeric_state
    entity_id: sensor.kueche_helligkeitssensor
  action:
  - data: {}
    entity_id: light.kueche
    service: light.turn_on
- id: '1590863622994'
  alias: Küche keine Bewegung -> Küchenlampe Aus
  description: ''
  trigger:
  - device_id: 3b59816422944600b79ce4faccfc87ec
    domain: binary_sensor
    entity_id: binary_sensor.kueche_bewegungssensor
    for:
      hours: 0
      minutes: 1
      seconds: 0
    platform: device
    type: no_motion
  condition:
  - condition: state
    entity_id: input_boolean.kueche_lichtschalter
    state: 'off'
  action:
  - data: {}
    entity_id: light.kueche
    service: light.turn_off
- id: '1590865975366'
  alias: Küchenlampe Aus -> Input_Boolean Aus
  description: ''
  trigger:
  - entity_id: light.kueche
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.kueche_lichtschalter
    service: input_boolean.turn_off
- id: '1593028783719'
  alias: Wohnzimmer Lichtschalter An (lang) -> Wohnzimmer Stehlampe An
  description: ''
  trigger:
  - device_id: 00cc41ffe8594568be7cba978e1ca1c9
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_long_press
  condition: []
  action:
  - data: {}
    entity_id: light.wohnzimmer_stehlampe
    service: light.turn_on
- id: '1593028825155'
  alias: Wohnzimmer Lichtschalter Aus (lang) -> Wohnzimmer Stehlampe Aus
  description: ''
  trigger:
  - device_id: 00cc41ffe8594568be7cba978e1ca1c9
    domain: deconz
    platform: device
    subtype: turn_off
    type: remote_button_long_press
  condition: []
  action:
  - data: {}
    entity_id: light.wohnzimmer_stehlampe
    service: light.turn_off
- id: '1593028891671'
  alias: Küche Lichtschalter An -> Input_Boolean An
  description: ''
  trigger:
  - device_id: af2308ef2a9b49e2a00a02292e707301
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.kueche_lichtschalter
    service: input_boolean.turn_on
- id: '1593932789090'
  alias: Waschmaschine An -> Input_Boolean An
  description: ''
  trigger:
  - above: '0'
    entity_id: sensor.waschmaschine_power
    for: 00:00:05
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.waschmaschine
    service: input_boolean.turn_on
- id: '1593932888055'
  alias: Waschmaschine Aus -> Input_Boolean Aus
  description: ''
  trigger:
  - below: '1'
    entity_id: sensor.waschmaschine_power
    for: 00:00:05
    platform: numeric_state
  condition:
  - condition: state
    entity_id: input_boolean.waschmaschine
    state: 'on'
  action:
  - data: {}
    entity_id: input_boolean.waschmaschine
    service: input_boolean.turn_off
- id: '1593933015571'
  alias: NTFY - Waschmaschine An
  description: ''
  trigger:
  - entity_id: input_boolean.waschmaschine
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Waschmaschine läuft
    service: notify.telegram
- id: '1593933080519'
  alias: NTFY - Waschmaschine Aus
  description: ''
  trigger:
  - entity_id: input_boolean.waschmaschine
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Waschmaschine ist fertig
    service: notify.telegram
- id: '1593933462152'
  alias: Geschirrspüler An -> Input_Boolean An
  description: ''
  trigger:
  - above: '0'
    entity_id: sensor.geschirrspueler_power
    for: 00:00:05
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.geschirrspueler
    service: input_boolean.turn_on
- id: '1593933525957'
  alias: Geschirrspüler Aus -> Input_Boolean Aus
  description: ''
  trigger:
  - below: '1'
    entity_id: sensor.geschirrspueler_power
    for: 00:00:05
    platform: numeric_state
  condition:
  - condition: state
    entity_id: input_boolean.geschirrspueler
    state: 'on'
  action:
  - data: {}
    entity_id: input_boolean.geschirrspueler
    service: input_boolean.turn_off
- id: '1593933585606'
  alias: NTFY - Geschirrspüler An
  description: ''
  trigger:
  - entity_id: input_boolean.geschirrspueler
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Geschirrspüler läuft
    service: notify.telegram
- id: '1593933634041'
  alias: NTFY - Geschirrspüler Aus
  description: ''
  trigger:
  - entity_id: input_boolean.geschirrspueler
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Geschirrspüler ist fertig
    service: notify.telegram
- id: '1593933862624'
  alias: S Geschirrspüler > Waschmaschine
  description: ''
  trigger:
  - entity_id: input_boolean.geschirrspueler
    for: 00:01:00
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.waschmaschine
    state: 'on'
  action:
  - data: {}
    entity_id: switch.geschirrspueler
    service: switch.turn_off
  - data:
      message: Waschmaschine läuft bereits. Geschirrspüler wurde ausgeschaltet
    service: notify.telegram
- id: '1593933954542'
  alias: S Waschmaschine > Geschirrspüler
  description: ''
  trigger:
  - entity_id: input_boolean.waschmaschine
    for: 00:01:00
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.geschirrspueler
    state: 'on'
  action:
  - data: {}
    entity_id: switch.waschmaschine
    service: switch.turn_off
  - data:
      message: Geschirrspüler läuft bereits. Waschmaschine wurde ausgeschaltet
    service: notify.telegram
