homeassistant:
  # https://www.home-assistant.io/docs/configuration/basic/
  # Overwrite automatic detections
  
  external_url: !secret base_url
  internal_url: !secret base_url

  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation

  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml

  # legacy auth
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret api_password

# Configure a default setup of Home Assistant (frontend, api, etc)
# https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/default_config/manifest.json
#default_config:
config:
alarm_control_panel: !include core/acp.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list automations
frontend: !include core/frontend.yaml
history: !include core/history.yaml
http: !include core/http.yaml
homekit: !include core/homekit.yaml
group: !include_dir_merge_named groups
#input_boolean: !include_dir_merge_named controls/input_booleans
logbook: !include core/logbook.yaml
lovelace:
  mode: yaml
person: #!include core/person.yaml
recorder: !include core/recorder.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
#script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list controls/switches
system_health:
updater:
api:
websocket_api:

# input helper
input_boolean: !include_dir_merge_named helper/input_boolean
input_text: !include_dir_merge_named helper/input_text
input_number: !include_dir_merge_named helper/input_number
input_datetime: !include_dir_merge_named helper/input_datetime
input_select: !include_dir_merge_named helper/input_select

# Alexa
alexa: !include services/alexa.yaml

# Cloudflare
#cloudflare: !include services/cloudflare.yaml

# Google Assistant
google_assistant: !include services/google_assistant.yaml

# Homematic
homematic: !include services/homematic.yaml

# Hue
# Press link button before starting HA for first setup
#hue: !include services/hue.yaml

# iOS integrations
# ios:
mobile_app:

light: !include_dir_merge_list lights

# Media Player
media_player: !include_dir_merge_list mediaplayers
apple_tv: !include services/mediaplayers/appletv.yaml
media_extractor: !include services/mediaplayers/mediaextractor.yaml

# MQTT
mqtt: !include services/mqtt.yaml

# Notifications
notify: !include services/notifier.yaml
telegram_bot: !include services/telegram.yaml

# Pilight
pilight: !include services/pilight.yaml

# Plex
# configured via UI as of 109
#plex: !include services/plex.yaml

# Shell commands
shell_command: !include shellcommands.yaml

# Tado
#tado: !include services/tado.yaml

# Tradfri
#tradfri: !include services/tradfri.yaml

# Wake on lan
wake_on_lan:
