homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Authentication
  auth_providers:
    - type: homeassistant
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 143
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml

# Defaults:
# Show links to resources in log and frontend
# introduction:
# Discover some devices automatically
# discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

api:

apple_tv: !include services/appletv.yaml

alexa: !include services/alexa.yaml

automation: !include automations.yaml
automation old: !include_dir_merge_list automations

binary_sensor: !include_dir_merge_list binary_sensors

# Enables configuration UI
config:

device_tracker: !include_dir_merge_list devicetracker

# Enables the frontend
frontend:

# Grouping
group: !include_dir_merge_named groups

# Enables support for tracking state changes over time.
history: !include services/history.yaml

homekit: !include services/homekit.yaml

# Homematic
homematic: !include services/homematic.yaml

http: !include services/http.yaml

hue: !include services/hue.yaml

input_number: !include controls/input_number.yaml

ios:

light: !include_dir_merge_list lights

# View all events in a logbook
logbook: !include services/logbook.yaml

# Enables a map showing the location of tracked devices
map:

media_extractor:
  default_query: best

# Media Players
media_player: !include_dir_merge_list mediaplayers

# Mqtt
mqtt: !include services/mqtt.yaml

notify: !include services/notifier.yaml

openuv: !include services/openuv.yaml

pilight: !include services/pilight.yaml

recorder: !include services/recorder.yaml

rest_command: !include services/rest_command.yaml

script: !include scripts.yaml

sensor: !include_dir_merge_list sensors

# Track the sun
sun:

switch: !include_dir_merge_list controls/switches

# Notifier Telegram
telegram_bot: !include services/telegram.yaml

tts: !include services/tts.yaml

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Wake on lan
wake_on_lan:

zone: !include zones.yaml
