homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  # lat:50.937989 long:11.589471
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 143
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization
  customize: !include customize.yaml

alexa:

automation: !include automations.yaml

# Apple TV
apple_tv: !include appletv.yaml

# Cameras
#camera: !include cameras.yaml

# Enable config screen
config:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

device_tracker: !include devicetracker.yaml

# Discover some devices automatically
#discovery:

# Enables the frontend
frontend:
  javascript_version: es5
#  javascript_version: latest

# Grouping
group: !include groups.yaml

# Enables support for tracking state changes over time.
history: !include history.yaml

homematic: !include homematic.yaml

http: !include http.yaml

hue: !include hue.yaml

ios:

# Show links to resources in log and frontend
#introduction:

light: !include lights.yaml

# View all events in a logbook
logbook:

# Logger settings
logger: !include logger.yaml

# Media Players
media_player: !include mediaplayers.yaml

# Mqtt
mqtt: !include mqtt.yaml

notify: !include notifier.yaml

pilight: !include pilight.yaml

recorder: !include recorder.yaml

sensor: !include sensors.yaml

sun:

switch: !include switches.yaml

# Notifier Telegram
telegram_bot: !include telegram.yaml

# Checks for available updates
updater:

zone: !include zones.yaml
