homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Authentication
  auth_providers:
    - type: homeassistant
    #- type: legacy_api_password
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 143
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization
  customize: !include customize.yaml

alexa: !include services/alexa.yaml

automation: !include automations.yaml
automation old: !include_dir_merge_list automations

# Apple TV
apple_tv: !include services/appletv.yaml

binary_sensor: !include_dir_merge_list binary_sensors

# Cameras
#camera: !include cameras.yaml

# Enable config screen
config:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

device_tracker: !include_dir_merge_list devicetracker

# Discover some devices automatically
#discovery:

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# Enables the frontend
frontend:
#  javascript_version: es5
#  javascript_version: latest

# Grouping
group: !include_dir_merge_named groups

# Enables support for tracking state changes over time.
history: !include services/history.yaml

homematic: !include services/homematic.yaml

http: !include services/http.yaml

hue: !include services/hue.yaml

ios:

# Show links to resources in log and frontend
#introduction:

light: !include_dir_merge_list lights

# View all events in a logbook
logbook:

# Logger settings
logger: !include services/logger.yaml

map:

media_extractor:
  default_query: best

# Media Players
media_player: !include_dir_merge_list mediaplayers

# Mqtt
mqtt: !include services/mqtt.yaml

notify: !include services/notifier.yaml

pilight: !include services/pilight.yaml

recorder: !include services/recorder.yaml

script: !include scripts.yaml

sensor: !include_dir_merge_list sensors

sun:

switch: !include_dir_merge_list switches

tado: !include services/tado.yaml

# Notifier Telegram
telegram_bot: !include services/telegram.yaml

tts: !include services/tts.yaml

# Checks for available updates
updater:

# Wake on lan
wake_on_lan:

zone: !include zones.yaml
