# Denon
- platform: denonavr
  host:  !secret denon_host
  name: Denon

# Sony TV
#- platform: braviatv
#  host: !secret tv_host

### Log severities
# critical
# fatal
# error
# warning
# warn
# info
# debug
# notset
