- platform: unifi
  host: !secret unifi_controller_host
  username: !secret unifi_controller_user
  password: !secret unifi_controller_pass
  ssid_filter:
    - '0612'
    - '0612bgn'
  verify_ssl: false
  detection_time: 300
