#broker: !secret mqtt_host
#port: !secret mqtt_port
certificate: /etc/ssl/certs/ca-certificates.crt
client_id: homeassistant
keepalive: 60
#username: !secret mqtt_username
#password: !secret mqtt_password
protocol: 3.1.1
sensor:
  - name: "Router Verbrauch Heute"
    state_topic: "rooms/flur/plug-router/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Router Verbrauch Gestern"
    state_topic: "rooms/flur/plug-router/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Router Verbrauch Gesamt"
    state_topic: "rooms/flur/plug-router/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Router Power"
    state_topic: "rooms/flur/plug-router/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    device_class: power
    unit_of_measurement: "W"
#  - name: "Router Voltage"
#    state_topic: "rooms/flur/plug-router/tele/SENSOR"
#    value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
#    unit_of_measurement: "V"
#  - name: "Router Power Factor"
#    state_topic: "rooms/flur/plug-router/tele/SENSOR"
#    value_template: '{{ value_json["ENERGY"]["Factor"] }}'
  - name: "NAS Verbrauch Heute"
    state_topic: "rooms/flur/plug-nas/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "NAS Verbrauch Gestern"
    state_topic: "rooms/flur/plug-nas/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "NAS Verbrauch Gesamt"
    state_topic: "rooms/flur/plug-nas/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "NAS Power"
    state_topic: "rooms/flur/plug-nas/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    device_class: power
    unit_of_measurement: "W"
#  - name: "NAS Voltage"
#  state_topic: "rooms/flur/plug-nas/tele/SENSOR"
#  value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
#  unit_of_measurement: "V"
#  - name: "NAS Power Factor"
#  state_topic: "rooms/flur/plug-nas/tele/SENSOR"
#  value_template: '{{ value_json["ENERGY"]["Factor"] }}'
####################################
###### Wohnzimmer
####################################
# Wohnzimmer Always On
  - name: "Wohnzimmer Verbrauch Heute"
    state_topic: "rooms/wohnzimmer/plug-wohnzimmer-alwayson/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Wohnzimmer Verbrauch Gestern"
    state_topic: "rooms/wohnzimmer/plug-wohnzimmer-alwayson/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Wohnzimmer Verbrauch Gesamt"
    state_topic: "rooms/wohnzimmer/plug-wohnzimmer-alwayson/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Wohnzimmer Power"
    state_topic: "rooms/wohnzimmer/plug-wohnzimmer-alwayson/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    device_class: power
    unit_of_measurement: "W"
# Wohnzimmer Stehlampe
  - name: "Wohnzimmer Stehlampe Verbrauch Heute"
    state_topic: "rooms/wohnzimmer/plug-wohnzimmer-stehlampe/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Wohnzimmer Stehlampe Verbrauch Gestern"
    state_topic: "rooms/wohnzimmer/plug-wohnzimmer-stehlampe/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Wohnzimmer Stehlampe Verbrauch Gesamt"
    state_topic: "rooms/wohnzimmer/plug-wohnzimmer-stehlampe/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Wohnzimmer Stehlampe Power"
    state_topic: "rooms/wohnzimmer/plug-wohnzimmer-stehlampe/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    device_class: power
    unit_of_measurement: "W"
####################################
###### Schlafzimmer
####################################
# Lavalampe
  - name: "Lavalamp Energy Today"
    state_topic: "rooms/bedroom/plug-lavalamp/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Lavalamp Energy Yesterday"
    state_topic: "rooms/bedroom/plug-lavalamp/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Lavalamp Energy Total"
    state_topic: "rooms/bedroom/plug-lavalamp/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Lavalamp Energy Power"
    state_topic: "rooms/bedroom/plug-lavalamp/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}' 
    device_class: power
    unit_of_measurement: "W"
####################################
###### Arbeitszimmer
####################################
# Schreibtisch Duc
  - name: "Schreibtisch Duc Verbrauch Heute"
    state_topic: "rooms/arbeitszimmer/plug-schreibtisch-duc/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Schreibtisch Duc Verbrauch Gestern"
    state_topic: "rooms/arbeitszimmer/plug-schreibtisch-duc/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Schreibtisch Duc Verbrauch Gesamt"
    state_topic: "rooms/arbeitszimmer/plug-schreibtisch-duc/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Schreibtisch Duc Power"
    state_topic: "rooms/arbeitszimmer/plug-schreibtisch-duc/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    device_class: power
    unit_of_measurement: "W"
# Schreibtisch Selina
  - name: "Schreibtisch Selina Verbrauch Heute"
    state_topic: "rooms/arbeitszimmer/plug-schreibtisch-selina/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Schreibtisch Selina Verbrauch Gestern"
    state_topic: "rooms/arbeitszimmer/plug-schreibtisch-selina/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Schreibtisch Selina Verbrauch Gesamt"
    state_topic: "rooms/arbeitszimmer/plug-schreibtisch-selina/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Schreibtisch Selina Power"
    state_topic: "rooms/arbeitszimmer/plug-schreibtisch-selina/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    device_class: power
    unit_of_measurement: "W"
####################################
###### Küche
####################################
# Backofen
  - name: "Backofen Verbrauch Heute"
    state_topic: "rooms/kueche/plug-backofen/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Backofen Verbrauch Gestern"
    state_topic: "rooms/kueche/plug-backofen/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Backofen Verbrauch Gesamt"
    state_topic: "rooms/kueche/plug-backofen/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Backofen Power"
    state_topic: "rooms/kueche/plug-backofen/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    device_class: power
    unit_of_measurement: "W"
# Geschirrspüler
  - name: "Geschirrspueler Verbrauch Heute"
    state_topic: "rooms/kueche/plug-geschirrspueler/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Geschirrspueler Verbrauch Gestern"
    state_topic: "rooms/kueche/plug-geschirrspueler/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Geschirrspueler Verbrauch Gesamt"
    state_topic: "rooms/kueche/plug-geschirrspueler/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Geschirrspueler Power"
    state_topic: "rooms/kueche/plug-geschirrspueler/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    device_class: power
    unit_of_measurement: "W"
# Kühlschrank
  - name: "Kuehlschrank Verbrauch Heute"
    state_topic: "rooms/kueche/plug-kuehlschrank/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Kuehlschrank Verbrauch Gestern"
    state_topic: "rooms/kueche/plug-kuehlschrank/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Kuehlschrank Verbrauch Gesamt"
    state_topic: "rooms/kueche/plug-kuehlschrank/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Kuehlschrank Power"
    state_topic: "rooms/kueche/plug-kuehlschrank/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    device_class: power
    unit_of_measurement: "W"
# Waschmaschine
  - name: "Waschmaschine Verbrauch Heute"
    state_topic: "rooms/kueche/plug-waschmaschine/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Waschmaschine Verbrauch Gestern"
    state_topic: "rooms/kueche/plug-waschmaschine/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Waschmaschine Verbrauch Gesamt"
    state_topic: "rooms/kueche/plug-waschmaschine/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Waschmaschine Power"
    state_topic: "rooms/kueche/plug-waschmaschine/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    device_class: power
    unit_of_measurement: "W"
####################################
###### Badezimmer
####################################
  - name: "Trockner Verbrauch Heute"
    state_topic: "rooms/badezimmer/plug-trockner/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Trockner Verbrauch Gestern"
    state_topic: "rooms/badezimmer/plug-trockner/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Trockner Verbrauch Gesamt"
    state_topic: "rooms/badezimmer/plug-trockner/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
    device_class: energy
    unit_of_measurement: "kWh"
  - name: "Trockner Power"
    state_topic: "rooms/badezimmer/plug-trockner/tele/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Power"] }}'
    device_class: power
    unit_of_measurement: "W"