- platform: yeelight
  devices:
    !secret yl-kueche_host:
      name: Kuechenlampe
      transition: 500
      use_music_mode: true
      save_on_change: false
    !secret yl-badezimmer_host:
      name: Badezimmer Lampe
      transition: 500
      use_music_mode: true
      save_on_change: false
    !secret yl-wohnzimmer-schreibtisch_host:
      name: Wohnzimmer Schreibtisch Lampe
      transition: 500
      use_music_mode: true
      save_on_change: false
