default_view:
  view: yes
  icon: mdi:home
  entities:
    - device_tracker.tle_tleipx
    - device_tracker.melinaip7
    - device_tracker.tleaw3
    - device_tracker.mspaw2
    - device_tracker.vwiip7
    - binary_sensor.oeq0169426_state
    - binary_sensor.someone_at_home
    - group.bahn
    - group.internet
    - group.weather_jena
    - group.uvinfo
    - sensor.travel_to_erfurt

Bahn:
  - sensor.nordschule_jena_to_stadtzentrum_lobdergraben_jena
  - sensor.stadtzentrum_lobdergraben_jena_to_nordschule_jena
