default_view:
  view: yes
  icon: mdi:home
  entities:
    - person.duc
    - person.melina
    - binary_sensor.oeq0169426_state
    - binary_sensor.someone_at_home
    - group.internet
    - group.weather_jena
#    - group.uvinfo
    - sensor.travel_to_erfurt
    - light.flurlampe

#Bahn:
#  - sensor.nordschule_jena_to_stadtzentrum_lobdergraben_jena
#  - sensor.stadtzentrum_lobdergraben_jena_to_nordschule_jena
