default_view:
  view: yes
  icon: mdi:home
  entities:
    - device_tracker.tle_tleipx
    - device_tracker.msp_mspip7
    - device_tracker.tleaw3
    - device_tracker.mspaw2
    - binary_sensor.oeq0169426_state
    - binary_sensor.someone_at_home
    - group.internet
    - group.weather_jena
    - group.uvinfo
    - sensor.travel_to_erfurt
    - light.flurlampe

#Bahn:
#  - sensor.nordschule_jena_to_stadtzentrum_lobdergraben_jena
#  - sensor.stadtzentrum_lobdergraben_jena_to_nordschule_jena
