- platform: template
  sensors:
    someone_at_home:
      friendly_name: "SomeoneAtHome"
      value_template: '{{ is_state("device_tracker.tleip7p","home") or is_state("device_tracker.melinaip7","home") }}'

