- platform: template
  sensors:
    router_power_cost:
      friendly_name: "Router Stromkosten"
      device_class: monetary
      unit_of_measurement: "€"
      value_template: >
        {% set usage = (states('sensor.router_verbrauch_gesamt') | float(0)) - (states('sensor.nas_verbrauch_gesamt') | float(0)) %}
        {% set cost = states('input_number.power_cost') | float(0) %}
        {{ (usage * cost) | round(2) }}

- platform: template
  sensors:
    nas_power_cost:
      friendly_name: "NAS Stromkosten"
      device_class: monetary
      unit_of_measurement: "€"
      value_template: >
        {% set usage = states('sensor.nas_verbrauch_gesamt') | float(0) %}
        {% set cost = states('input_number.power_cost') | float(0) %}
        {{ (usage * cost) | round(2) }}

####################################
###### Wohnzimmer
####################################
# Wohnzimmer Always On
- platform: template
  sensors:
    living_room_tv_power_cost:
      friendly_name: "Wohnzimmer TV Stromkosten"
      device_class: monetary
      unit_of_measurement: "€"
      value_template: >
        {% set usage = states('sensor.wohnzimmer_verbrauch_gesamt') | float(0) %}
        {% set cost = states('input_number.power_cost') | float(0) %}
        {{ (usage * cost) | round(2) }}

# Wohnzimmer Stehlampe
- platform: template
  sensors:
    living_room_floor_lamp_power_cost:
      friendly_name: "Wohnzimmer Stehlampe Stromkosten"
      device_class: monetary
      unit_of_measurement: "€"
      value_template: >
        {% set usage = states('sensor.wohnzimmer_stehlampe_verbrauch_gesamt') | float(0) %}
        {% set cost = states('input_number.power_cost') | float(0) %}
        {{ (usage * cost) | round(2) }}

####################################
###### Schlafzimmer
####################################
# Lavalampe
- platform: template
  sensors:
    lavalamp_power_cost:
      friendly_name: "Lavalampe Stromkosten"
      device_class: monetary
      unit_of_measurement: "€"
      value_template: >
        {% set usage = states('sensor.lavalamp_energy_total') | float(0) %}
        {% set cost = states('input_number.power_cost') | float(0) %}
        {{ (usage * cost) | round(2) }}

####################################
###### Arbeitszimmer
####################################
# Schreibtisch Duc
- platform: template
  sensors:
    desk_duc_power_cost:
      friendly_name: "Ducs Schreibtisch Stromkosten"
      device_class: monetary
      unit_of_measurement: "€"
      value_template: >
        {% set usage = states('sensor.schreibtisch_duc_verbrauch_gesamt') | float(0) %}
        {% set cost = states('input_number.power_cost') | float(0) %}
        {{ (usage * cost) | round(2) }}

# Schreibtisch Selina
- platform: template
  sensors:
    desk_selina_power_cost:
      friendly_name: "Selinas Schreibtisch Stromkosten"
      device_class: monetary
      unit_of_measurement: "€"
      value_template: >
        {% set usage = states('sensor.schreibtisch_selina_verbrauch_gesamt') | float(0) %}
        {% set cost = states('input_number.power_cost') | float(0) %}
        {{ (usage * cost) | round(2) }}

####################################
###### Küche
####################################
# Backofen
- platform: template
  sensors:
    oven_power_cost:
      friendly_name: "Backofen Stromkosten"
      device_class: monetary
      unit_of_measurement: "€"
      value_template: >
        {% set usage = states('sensor.backofen_verbrauch_gesamt') | float(0) %}
        {% set cost = states('input_number.power_cost') | float(0) %}
        {{ (usage * cost) | round(2) }}

# Geschirrspüler
- platform: template
  sensors:
    dishwasher_power_cost:
      friendly_name: "Geschirrspüler Stromkosten"
      device_class: monetary
      unit_of_measurement: "€"
      value_template: >
        {% set usage = states('sensor.geschirrspueler_verbrauch_gesamt') | float(0) %}
        {% set cost = states('input_number.power_cost') | float(0) %}
        {{ (usage * cost) | round(2) }}

# Kühlschrank
- platform: template
  sensors:
    refridgerator_power_cost:
      friendly_name: "Kühlschrank Stromkosten"
      device_class: monetary
      unit_of_measurement: "€"
      value_template: >
        {% set usage = states('sensor.kuehlschrank_verbrauch_gesamt') | float(0) %}
        {% set cost = states('input_number.power_cost') | float(0) %}
        {{ (usage * cost) | round(2) }}

# Waschmaschine
- platform: template
  sensors:
    washer_power_cost:
      friendly_name: "Waschmaschine Stromkosten"
      device_class: monetary
      unit_of_measurement: "€"
      value_template: >
        {% set usage = states('sensor.waschmaschine_verbrauch_gesamt') | float(0) %}
        {% set cost = states('input_number.power_cost') | float(0) %}
        {{ (usage * cost) | round(2, default=2) }}


####################################
###### Badezimmer
####################################
- platform: template
  sensors:
    dryer_power_cost:
      friendly_name: "Trockner Stromkosten"
      device_class: monetary
      unit_of_measurement: "€"
      value_template: >
        {% set usage = states('sensor.trockner_verbrauch_gesamt') | float(0) %}
        {% set cost = states('input_number.power_cost') | float(0) %}
        {{ (usage * cost) | round(2) }}
