- platform: mqtt
  name: "Waschmaschine Verbrauch Heute"
  state_topic: "rooms/badezimmer/plug-waschmaschine/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Today"] }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "Waschmaschine Verbrauch Gestern"
  state_topic: "rooms/badezimmer/plug-waschmaschine/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "Waschmaschine Verbrauch Gesamt"
  state_topic: "rooms/badezimmer/plug-waschmaschine/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "Waschmaschine Power"
  state_topic: "rooms/badezimmer/plug-waschmaschine/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: "W"
- platform: mqtt
  name: "Waschmaschine Voltage"
  state_topic: "rooms/badezimmer/plug-waschmaschine/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
  unit_of_measurement: "V"
- platform: mqtt
  name: "Waschmaschine Power Factor"
  state_topic: "rooms/badezimmer/plug-waschmaschine/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Factor"] }}'

- platform: mqtt
  name: "Wohnzimmer Verbrauch Heute"
  state_topic: "rooms/wohnzimmer/plug-tv/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Today"] }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "Wohnzimmer Verbrauch Gestern"
  state_topic: "rooms/wohnzimmer/plug-tv/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "Wohnzimmer Verbrauch Gesamt"
  state_topic: "rooms/wohnzimmer/plug-tv/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Total"] }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "Wohnzimmer Power"
  state_topic: "rooms/wohnzimmer/plug-tv/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Power"] }}'
  unit_of_measurement: "W"
- platform: mqtt
  name: "Wohnzimmer Voltage"
  state_topic: "rooms/wohnzimmer/plug-tv/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
  unit_of_measurement: "V"
- platform: mqtt
  name: "Wohnzimmer Power Factor"
  state_topic: "rooms/wohnzimmer/plug-tv/tele/SENSOR"
  value_template: '{{ value_json["ENERGY"]["Factor"] }}'

