- platform: mqtt
  state_topic: "rooms/wohnzimmer/temperature"
  name: 'Wohnzimmer Temperature'
  unit_of_measurement: '째C'
- platform: mqtt
  state_topic: "rooms/wohnzimmer/humidity"
  name: 'Wohnzimmer Humidity'
  unit_of_measurement: '%'

- platform: mqtt
  state_topic: "rooms/schlafzimmer/temperature"
  name: 'Schlafzimmer Temperature'
  unit_of_measurement: '째C'
- platform: mqtt
  state_topic: "rooms/schlafzimmer/humidity"
  name: 'Schlafzimmer Humidity'
  unit_of_measurement: '%'

- platform: mqtt
  state_topic: "rooms/badezimmer/temperature"
  name: 'Badezimmer Temperature'
  unit_of_measurement: '째C'
- platform: mqtt
  state_topic: "rooms/badezimmer/humidity"
  name: 'Badezimmer Humidity'
  unit_of_measurement: '%'

- platform: mqtt
  state_topic: "rooms/kueche/temperature"
  name: 'Kueche Temperature'
  unit_of_measurement: '째C'
- platform: mqtt
  state_topic: "rooms/kueche/humidity"
  name: 'Kueche Humidity'
  unit_of_measurement: '%'
