- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - temperature
    - apparent_temperature
    - temperature_high
    - temperature_low
    - wind_speed
    - humidity
  units: si
  update_interval:
    minutes: 2
  language: de
