- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
    - 0
  monitored_conditions:
    - summary
    - temperature
    - apparent_temperature
    - temperature_high
    - temperature_low
    - wind_speed
    - humidity
  units: si
  update_interval:
    minutes: 10
  language: de
