- platform: ping
  host: !secret macmini_host
  name: MacMini

- platform: ping
  host: !secret printer_host
  name: Printer

- platform: ping
  host: !secret database_host
  name: Database

- platform: ping
  host: !secret bitbucket_host
  name: Bitbucket

- platform: ping
  host: !secret dns_server_host
  name: DNS Server

- platform: ping
  host: !secret homebridge_host
  name: Homebridge

- platform: ping
  host: !secret huebridge_host
  name: Philips Hue Bridge

- platform: ping
  host: !secret mqtt_host
  name: MQTT

- platform: ping
  host: !secret atv4_host
  name: Apple TV Schlafzimmer

- platform: ping
  host: !secret atv4k_host
  name: Apple TV Wohnzimmer

- platform: ping
  host: !secret seafile_host
  name: Seafile

- platform: ping
  host: !secret wohnzimmer_kamera_1_host
  name: Wohnzimmer Kamera 1

- platform: ping
  host: !secret tado_bridge_host
  name: Tado Bridge

- platform: ping
  host: !secret alexa_kueche_host
  name: Alexa Kueche
