- platform: template
  switches:
    wohnzimmer_anlage:
      friendly_name: Wohnzimmer Anlage
      icon_template: mdi:television
      value_template: "{{ is_state('media_player.denon_avr', 'on') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.denon_avr
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.denon_avr
