- platform: template
  switches:
    manualfeed:
      friendly_name: 'Snack'
      value_template: '{{ states("switch.manualfeed") }}'
      turn_on:
        service: rest_command.feeder_feed
        data_template:
          feedamount: "{{ states('input_number.feedamount') | int }}"
      turn_off:
    feed60:
      friendly_name: '60g'
      value_template: '{{ states("switch.feed60") }}'
      turn_on:
        service: rest_command.feeder_feed
        data_template:
          feedamount: "60"
      turn_off:
