- platform: mqtt
  name: "Waschmaschine"
  state_topic: "rooms/badezimmer/plug-waschmaschine/stat/POWER"
  command_topic: "rooms/badezimmer/plug-waschmaschine/cmnd/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
