- platform: pilight
  switches:
    Schlafzimmer TV Steckdose:
      on_code:
        protocol: kaku_switch
        id: !secret plugset1_id
        unit: 0
        state: 'on'
        'on': 1
      off_code:
        protocol: kaku_switch
        id: !secret plugset1_id
        unit: 0
        state: 'off'
        'off': 0
    Schlafzimmer Ventilator Steckdose:
      on_code:
        protocol: kaku_switch
        id: !secret plugset1_id
        unit: 1
        state: 'on'
        'on': 1
      off_code:
        protocol: kaku_switch
        id: !secret plugset1_id
        unit: 1
        state: 'off'
        'off': 0
    Arbeitszimmer Alexa Steckdose:
      on_code:
        protocol: kaku_switch
        id: !secret plugset1_id
        unit: 2
        state: 'on'
        'on': 1
      off_code:
        protocol: kaku_switch
        id: !secret plugset1_id
        unit: 2
        state: 'off'
        'off': 0
    Wohnzimmer Ventilator Steckdose:
      on_code:
        protocol: kaku_switch
        id: !secret plugset2_id
        unit: 0
        state: 'on'
        'on': 1
      off_code:
        protocol: kaku_switch
        id: !secret plugset2_id
        unit: 0
        state: 'off'
        'off': 0
    Wohnzimmer Alexa Steckdose:
      on_code:
        protocol: kaku_switch
        id: !secret plugset2_id
        unit: 1
        state: 'on'
        'on': 1
      off_code:
        protocol: kaku_switch
        id: !secret plugset2_id
        unit: 1
        state: 'off'
        'off': 0
