- platform: mqtt
  name: "Trockner"
  state_topic: "rooms/badezimmer/plug-trockner/stat/POWER"
  command_topic: "rooms/badezimmer/plug-trockner/cmnd/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  retain: false

