- platform: template
  switches:
    braviatv:
      friendly_name: Wohnzimmer Fernseher
      icon_template: mdi:television
      value_template: "{{ is_state('media_player.kd55xe9005', 'on') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.kd55xe9005
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.kd55xe9005
