# WOL
# these are actually 3 switches
# 1. wake_on_lan switch for turning the computer on
# 2. command_line switch for turning the computer off
# 3. the actual switch that is shown in the UI
#    - checks wake_on_lan switch to determine whether the computer is on
#    - on: triggers wake_on_lan switch
#    - off: triggers command_line switch


- platform: wake_on_lan
  mac: !secret computer_tle_mac_address
  name: "Ducs Computer"
  host: !secret computer_tle_host
  turn_off:
    service: switch.turn_off
    target:
        entity_id:
          - switch.shutdown_computer_tle

- platform: command_line
  switches:
    shutdown_computer_tle:
      command_off: !secret computer_tle_shutdown_cmd

- platform: wake_on_lan
  mac: !secret computer_sel_mac_address
  name: "Selinas Computer"
  host: !secret computer_sel_host
  turn_off:
    service: switch.turn_off
    target:
        entity_id:
          - switch.shutdown_computer_sel

- platform: command_line
  switches:
    shutdown_computer_sel:
      command_off: !secret computer_sel_shutdown_cmd

- platform: wake_on_lan
  mac: !secret computer_wohnzimmer_mac_address
  name: "Wohnzimmer Computer"
  host: !secret computer_wohnzimmer_host
  turn_off:
    service: switch.turn_off
    target:
        entity_id:
          - switch.shutdown_computer_wohnzimmer

- platform: command_line
  switches:
    shutdown_computer_wohnzimmer:
      command_off: !secret computer_wohnzimmer_shutdown_cmd
